name: CI - React + Express

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      # =========================
      # Backend - Express
      # =========================
      - name: Instalar dependencias del backend
        working-directory: ./server
        run: npm install

      - name: Lint del backend
        working-directory: ./server
        run: npm run lint

      - name: Pruebas del backend
        working-directory: ./server
        run: npm run test

      # =========================
      # Frontend - React + Vite
      # =========================
      - name: Instalar dependencias del frontend
        working-directory: ./client
        run: npm install

      - name: Build del frontend
        working-directory: ./client
        run: npm run build

      - name: Lint del frontend
        working-directory: ./client
        run: npm run lint

      - name: Pruebas del frontend
        working-directory: ./client
        run: npm run test