name: CI - Fullstack React + Express

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  fullstack-ci:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      # ========================
      # Backend (Express)
      # ========================
      - name: Instalar dependencias del backend
        working-directory: ./backend
        run: npm install

      - name: Lint del backend
        working-directory: ./backend
        run: npm run lint

      - name: Test del backend
        working-directory: ./backend
        run: npm run test

      # ========================
      # Frontend (React + Vite)
      # ========================
      - name: Instalar dependencias del frontend
        working-directory: ./frontend
        run: npm install

      - name: Lint del frontend
        working-directory: ./frontend
        run: npm run lint

      - name: Build del frontend
        working-directory: ./frontend
        run: npm run build

      - name: Test del frontend
        working-directory: ./frontend
        run: npm run test